### ISSUE TITLE
False error:  root and self types should sometimes be application/geo+json

### ISSUE THREAD

**Issue by philvarner** [stac-utils/stac-api-validator#206]
These from stac-server -- likely they're application/geo+json

- / : Link[rel=root] type is not application/json
- / : Link[rel=self] type is not application/json

**Comment by PanierAvide** [comment]
Hello,

I'm using version 0.4.2 of STAC API Validator running against a API following v1.0.0-rc.2, isn't the landing page supposed to be `application/json` instead of `application/geo+json` ? Because test now fails if `application/json` is returned, it expects geojson mimetype. Or did I miss something ?

Best regards.

**Comment by philvarner** [comment]
You are correct, I think this issue was written confusingly. Are you talking about the `type` field in the Link, or the `content-type` header in the response?

**Comment by philvarner** [comment]
ah, this is still a bug in 0.4.2, not sure what I did there. Will file another issue.
